spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cryptocurrency_simulator
    username: simulator
    password: simulator
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

    # OSIV 끄기
    open-in-view: false

  redis:
    port: 6379
    host: localhost


logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

server:
  port: 9090

JWT:
  SECRET:
    KEY: N0ppQjdLZUE2NGlFNjRLWUlPcTNnT3lYdmV1THBBPT0=

  ACCESS:
    TOKEN:
      VALIDITY: 6000000 # 100분